### ISSUE TITLE
代码压缩包

### ISSUE THREAD

**Issue by wu-kai** [FE-help/testCode#3]
![image](https://user-images.githubusercontent.com/12909883/147812919-678bf4ba-c510-4b80-94b9-ab5d2e39faff.png)

以后代码压缩成zip后，添加到项目的这个目录下，然后push代码

**Comment by wu-kai** [comment]
ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAj3LsdwIjRon5cPUkoDExQtQlC2Mh4yNbVTAzZGfHy0C587DOEMObrA2DdE15zEPaoOryGyZ466e5IwLPOz7Oj7aMmFnlzPuTmBvV39w4hc0rX/QifTob2YnQuPCA98t4lA2pFPvWDTPM5u4+ZkJ1dQJ7yYRMPlB3OMD2Tj6Q8ZHESEPhrkXY2UzWKYmH2b3codWmrpI88rO6oTg6aM73V163oJs2oH5Iz5tkCPWSJyAyafjzG8K1v6mNK9nSyHWQsbEj8wKV80tBu5Cibwf9FcaoWHp39kI6iX9wqg/w/mGT/yPpEwdqNfUt6gs1dpsTjo8+lTfdvzAwauWgrvRYkQ== rsa-key-20220105


@oaying   密钥格式应该是这样

**Comment by oaying** [comment]
![image](https://user-images.githubusercontent.com/93694046/148149704-6a0676f0-ba73-47ce-8227-9e283f1b061e.png)
那要重新生成一个吗，  这个生成在哪儿来着.............................

**Comment by wu-kai** [comment]
你看这个密钥格式呀，你用.ppk里面的内容可以拼凑出来

**Comment by wu-kai** [comment]
![image](https://user-images.githubusercontent.com/12909883/148149845-91d0f4a6-28ec-41e3-94ab-3a4437af962c.png)
 
用   Pukky-user-key-file-2  +   public-line下面的一长串    +  comment

**Comment by wu-kai** [comment]
生成密钥的话  是工具 -> 导入或新建  SHH密钥

**Comment by oaying** [comment]
![image](https://user-images.githubusercontent.com/93694046/148150772-bbc8c0f7-8299-465f-b7db-b033f4ed1a3b.png)
b不得行....

**Comment by wu-kai** [comment]
那就重新生成一个

**Comment by oaying** [comment]
![image](https://user-images.githubusercontent.com/93694046/148151882-4c341352-f3c7-45c0-8754-1ab5aa61b611.png)
把箭头里面的内容复制到git添加密钥的地方  下面划线的save哪个来着

**Comment by wu-kai** [comment]
save private  保存为私有key  然后你还要设置密码
![image](https://user-images.githubusercontent.com/12909883/148152075-eef53771-6488-49fa-9047-70d53bc694ea.png)


![image](https://user-images.githubusercontent.com/12909883/148152085-12fcdf01-2ba5-4b1a-ac22-9c5a83a978bc.png)

这个里面的内容  你最好创建一个文本来保存一下    或者你直接创建一个issue 来保存  


下次用的时候好找


不过每次创建一个ssh key 也无所谓

**Comment by oaying** [comment]
O了 我代码zip压缩提交了  问题也描述了  follow页面没有接口  你可以直接运行看效果
