### ISSUE TITLE
首次放代码进仓库

### ISSUE THREAD

**Issue by oaying** [FE-help/testCode#5]
![image](https://user-images.githubusercontent.com/93694046/148345609-5277374c-26f9-48a4-8afe-2a022ad894c8.png)
然后先克隆下来？ 我总记得你给我说过 但是我总觉得我又有点记不清楚
我现在本地已经有代码的文件夹了
![image](https://user-images.githubusercontent.com/93694046/148345717-b7a99ed5-ed8c-4b09-80b7-e33541920036.png)
bu不会把我的文件夹干掉吗？

**Comment by oaying** [comment]
![image](https://user-images.githubusercontent.com/93694046/148345865-3db1ba7e-8505-46db-8530-b8a6189a0a66.png)
补充yix一下 你看我现在是在文件夹下面了哈

**Comment by wu-kai** [comment]
![image](https://user-images.githubusercontent.com/12909883/148348531-1e6d1c3c-d433-4790-a699-af5abd488528.png)

这就是在d盘下面创建test项目

![image](https://user-images.githubusercontent.com/12909883/148348691-0d01f0f7-efa1-4856-a95f-bff792ec5a42.png)


这是在D盘下的app_h5文件夹下面创建test项目
