### ISSUE TITLE
关于全局样式

### ISSUE THREAD

**Issue by wu-kai** [FE-help/testCode#7]
![image](https://user-images.githubusercontent.com/12909883/150515869-71911980-5c2d-4fb3-9b49-5fd7003c6f3a.png)

首先菜单栏添加固定宽度

![image](https://user-images.githubusercontent.com/12909883/150516016-a202545a-fc53-4b64-ab98-841e67e13fc2.png)

然后内容栏添加 自适应宽度   宽度计算方式   100% - 菜单栏宽度

效果如下，浏览器宽度变化的时候，不会出现横向滚动条，不会影响横向样式
![wb6](https://user-images.githubusercontent.com/12909883/150516382-6e919729-7513-4f2c-aaaa-591a03420788.gif)

然后内容的表格需要在表格内添加  一个横向滚动条

**Comment by wu-kai** [comment]
![image](https://user-images.githubusercontent.com/12909883/150714931-c0dadddd-b341-4a67-97f3-8b290a6d0ef7.png)
首先是路由盒子  main.vue的高度要设置为100vh

![image](https://user-images.githubusercontent.com/12909883/150714975-95d85de9-3e51-49d2-8021-235935227733.png)
![image](https://user-images.githubusercontent.com/12909883/150715004-5dc86260-02ef-4352-a5b9-441e9a4ef0e7.png)
然后是你的内容页面，表格高度应该是    100vh 减去 搜索栏的高度  以及下面分页的高度

![image](https://user-images.githubusercontent.com/12909883/150715028-13b167b8-b613-4a97-b8a5-694ac9dbf402.png)

最后是你的菜单栏要加滚动条，滚动条高度设置为   100vh 减去  上面头像的高度   最后减的10px是为了让菜单栏底部出现一点空白，可以看出来滚动条的底部在哪里。  减不减都可以

**Comment by oaying** [comment]
![image](https://user-images.githubusercontent.com/93694046/150716346-eacd0f5d-928c-42b0-a1f4-d4a2a4c817cc.png)
这里为什么是减去了270诶 
![image](https://user-images.githubusercontent.com/93694046/150716384-443b4265-20c1-4e27-8532-897bf42d2922.png)
这儿不是应该减去100+15的margin 115哇
